package com.java;

public class Introduction {

	public static void main(String[] args) {
		// TODO Auto-generated method stub
//System.out.println("Hello World!");
//System.out.println("I am learning Java.");
//System.out.println("It is awesome!");
//System.out.println("This sentence will work");
////System.out.println(This sentence will produce an error);
//System.out.print("Hello World!  ");
//System.out.print("I will print on the same line. ");
//System.out.println(3);
//System.out.println(358);
//System.out.println(50000);
//System.out.println(3+3);
//System.out.println(3 + 3);
//System.out.println(2 * 5);
//System.out.println("Hello World"); // This is a comment
//String name="John";
//System.out.println(name);
//int myNum=15;
//System.out.println(myNum);
//int myNum;
//myNum=15;
//System.out.println(myNum);
//int myNum=15;
//myNum=20;
//System.out.println(myNum);
//final int myNum=15;
//myNum=20;
//int myNum=5;
//float myFloatNum=5.99f;
char myLetter='D';
boolean myBool=true;
String myText="Hello";
String name="John";
//System.out.println("Hello " + name);
String firstName="John";
String lastName="Doe";
String fullName=firstName + lastName;
//System.out.println(fullName);
//int x=5;
//int y=6;
//int z=50;
//System.out.println(x + y);
//System.out.println(x+y+z);
//int x,y,z;
//x=y=z=50;
//System.out.println(x+y+z);
int minutesPerHour=60;
int m=60;
//byte myNum=100;
//System.out.println(myNum);
//short myNum=5000;
//System.out.println(myNum);
//int myNum=100000;
//System.out.println(myNum);
//long myNum=1500000000L;
//System.out.println(myNum);
float myFloatNum=5.75f;
//System.out.println(myFloatNum);
double myDoubleNum=19.99d;
//System.out.println(myDoubleNum);
float f1=35e3f;
double d1=12E4d;
//System.out.println(f1);
//System.out.println(d1);
boolean isJavaFun=true;
boolean isFishTasty=false;
//System.out.println(isJavaFun);
//System.out.println(isFishTasty);
char myGrade='B';
//System.out.println(myGrade);
char myVar1=65,myVar2=66,myVar3=67;
//System.out.println(myVar1);
//System.out.println(myVar2);
//System.out.println(myVar3);
String greeting="Hello World";
//System.out.println(greeting);
int myInt=9;
double myDouble=myInt;
//System.out.println(myInt);
//System.out.println(myDouble);
int sum1=100+50;
int sum2=sum1+250;
int sum3=sum2+sum2;
int x=10;
x+=5;
//System.out.println(x);
x-=5;
//System.out.println(x);
x*=5;
//System.out.println(x);
x/=5;
//System.out.println(x);
x%=5;
//System.out.println(x);
x=50;
x&=5;
//System.out.println(x);
x|=5;
//System.out.println(x);
x^=5;
//System.out.println(x);
x>>=3;
//System.out.println(x);
x<<=3;
//System.out.println(x);
String txt="ABCDEFGHIJKLMNOPQRSTUVWXYZ";
//System.out.println("The length of the txt string is: " +txt.length());
txt="Hello World!";
txt.toLowerCase();
//System.out.println(txt.toLowerCase());
//System.out.println(txt.toUpperCase());
txt="Please locate where 'locate' occurs!";
//System.out.println(txt.indexOf("locate"));
//System.out.println(firstName + " " + lastName );
//System.out.println(firstName.concat(lastName));
//System.out.println(firstName   + " ".concat(lastName));
String xa="10";
String xb="20";
String xc=xa+xb;
xc=xa + " " + xb;
//System.out.println(xc);
int ia=20;
String sc=xa+ia;
//System.out.println(sc);

	}

}
